[[param]]
name = "hintfile"
type = "String"
default = "\"./bitcoin.hints\".into()"
doc = "The path to your `bitcoin.hints` file that will be used for IBD"

[[param]]
name = "blocks_dir"
type = "String"
default = "\"./blockfiles\".into()"
doc = "Directory where you would like to store the bitcoin blocks"

[[param]]
name = "network"
type = "String"
default = "\"bitcoin\".into()"
doc = "The bitcoin network to operate on. Options are `bitcoin` or `signet`"

[[param]]
name = "ping_timeout"
type = "u64"
default = "15"
doc = "The time a peer has to respond to a `ping` message. Pings are sent aggressively throughout IBD to find slow peers."

[[param]]
name = "tcp_timeout"
type = "u64"
default = "2"
doc = "The maximum time to establish a connection"

[[param]]
name = "read_timeout"
type = "u64"
default = "2"
doc = "The maximum time to read from a TCP stream until the connection is killed."

[[param]]
name = "write_timeout"
type = "u64"
default = "2"
doc = "The maximum time to write to a TCP stream until the connection is killed."
