[package]
name = "accumulator"
version = "0.1.0"
edition = "2024"

[dependencies]
bitcoin = { workspace = true } 

[dev-dependencies]
bitcoin = { workspace = true, default-features = true } 
rusqlite = { version = "0.36.0", features = ["bundled"] }
